Repository dirigeants/klasa-pieces, pull requests merged in 2018-08, with the labels that each got.

#86 Create biggify.js
  commands/Fun/biggify.js
Labels: Meta: New Pieces

#88 Updated all providers for latest SG
  providers/cockroachdb.js
  providers/firestore.js
  providers/level.js
  providers/mongodb.js
  providers/mssql.js
  providers/mysql.js
  providers/neo4j.js
  providers/postgresql.js
  providers/rebirthdb.js
  providers/rethinkdb.js
  providers/sqlite.js
Labels: Type: Maintenance

#91 Improve cleanup task by sweeping old messages
  tasks/cleanup.js
Labels: Type: Caching

#78 Add redis provider.
  providers/redis.js
Labels: Meta: New Pieces

#95 fix: await the creation of the database if missing
  providers/rethinkdb.js
Labels: Meta: Bug-Fix
