Repository dirigeants/klasa-pieces, pull requests merged in 2018-04, with the labels that each got.

#45 Updated API in cat.js -TheFloppyBanana
  commands/Misc/cat.js
Labels: Meta: Maintenance

#46 Shortened a string
  monitors/nomention.js
Labels: Enhancement, Meta: Maintenance

#50 Added reset subcommand -TheFloppyBanana
  commands/Configuration/prefix.js
Labels: Type: Enhancement

#37 Info command text changes for other languages
  languages/de-DE.js
  languages/es-ES.js
  languages/fr-FR.js
  languages/it-IT.js
  languages/ro-RO.js
  languages/tr-TR.js
  package.json
Labels: Meta: Documentation, Status: Help Wanted, Type: Maintenance

#54 Chuck Norris Joke Command
  commands/Fun/chucknorris.js
Labels: Meta: New Pieces
