Repository dirigeants/klasa-pieces, pull requests merged in 2018-06, with the labels that each got.

#64 Added the Firestore provider
  providers/firestore.js
Labels: Meta: New Pieces

#71 Made it complaint with issue #328
  providers/firestore.js
  providers/neo4j.js
Labels: Bug: Fixed, Type: Maintenance

#70 getAll() changes in all SQL providers
  providers/mssql.js
  providers/mysql.js
  providers/postgresql.js
  providers/sqlite.js
Labels: Type: Maintenance

#73 Update the rest of the providers for SGv2.2.0
  providers/mongodb.js
  providers/nedb.js
Labels: Meta: Refactor, Type: Maintenance, Type: Performance

#62 Add some commands
  commands/Fun/markov.js
  commands/Fun/randquote.js
  commands/Fun/trumpquote.js
  commands/Fun/wordcloud.js
  commands/Tools/followage.js
  commands/Tools/hastebin.js
  commands/Tools/movie.js
  commands/Tools/randomreddit.js
  commands/Tools/subreddit.js
  commands/Tools/topinvites.js
  commands/Tools/wikipedia.js
  commands/Tools/wolfram.js
Labels: Meta: New Pieces

#79 Who did this v2
  finalizers/deleteCommand.js
  inhibitors/deleteCommand.js
Labels: Bug: Fixed
