Repository dirigeants/klasa-pieces, pull requests merged in 2018-03, with the labels that each got.

#30 Create wikipedia.js
  commands/Tools/wikipedia.js
Labels: Meta: New Pieces

#34 Create faceapp.js
  commands/Fun/faceapp.js
Labels: Meta: New Pieces

#36 Create prefix.js
  commands/Configuration/prefix.js
Labels: Meta: New Pieces

#35 Fix
  commands/Tools/price.js
Labels: Enhancement

#39 Fix postgres provider and other SQL provider
  providers/mssql.js
  providers/mysql.js
  providers/postgresql.js
  providers/sqlite.js
Labels: Bug: Fixed, Meta: Maintenance

#42 Made a variable look cooler 😎
  providers/mongodb.js
Labels: Enhancement
