Repository dirigeants/klasa-pieces, pull requests merged in 2018-10, with the labels that each got.

#111 [Feat] add random lizard command
  commands/Misc/lizard.js
Labels: Meta: New Pieces

#110 [Feat] add duck command
  commands/Misc/duck.js
Labels: Meta: New Pieces

#109 misc: Migrate to rest arguments
  commands/Misc/echo.js
  commands/Moderation/ban.js
  commands/Moderation/kick.js
  commands/Moderation/mute.js
  commands/Moderation/softban.js
  commands/Moderation/unban.js
  commands/Moderation/unmute.js
  commands/Tools/remindme.js
  events/.createFolder
  finalizers/.createFolder
Labels: Meta: Cleanup

#123 Update fr-FR
  languages/fr-FR.js
Labels: Type: Maintenance

#129 language: klasa#452 - no embed invite link
  languages/de-DE.js
  languages/es-ES.js
  languages/fr-FR.js
  languages/it-IT.js
  languages/ro-RO.js
  languages/tr-TR.js
Labels: Type: Maintenance

#112 [Feat] add random meme command
  commands/Fun/meme.js
Labels: Meta: New Pieces

#134 add return statement
  routes/pieces.js
Labels: Meta: Bug-Fix
