Repository dirigeants/klasa-pieces, pull requests merged in 2018-09, with the labels that each got.

#94 fix: mongodb - update overwrites data in SchemaFolders
  providers/mongodb.js
Labels: Meta: Bug-Fix, Type: Enhancement

#93 add: member name argument
  arguments/membername.js
Labels: Meta: Feature, Meta: New Pieces

#99 add: user auth in the RethinkDB provider
  providers/rethinkdb.js
Labels: Type: Enhancement

#100 Add rateLimit event
  events/rateLimit.js
Labels: Meta: New Pieces

#101 fix: Remove stupid in sweeper
  tasks/cleanup.js
Labels: Meta: Cleanup

#103 better roleinfo timestamp
  commands/Tools/role-info.js
Labels: Meta: Cleanup, Type: Enhancement

#102 Update Extendables To Latest Klasa
  extendables/ask.js
  extendables/awaitReply.js
  extendables/fetchImage.js
  extendables/message.js
Labels: Type: Maintenance

#106 Fixed connection pool termination for Postgres
  providers/postgresql.js
Labels: Meta: Bug-Fix

#107 Fix the role.js route
  routes/role.js
Labels: Bug: Fixed, Type: Maintenance
