Repository dirigeants/klasa-pieces, pull requests merged in 2018-07, with the labels that each got.

#81 Update kick.js
  commands/Moderation/kick.js
Labels: Bug: Fixed, Type: Maintenance

#75 Added the CockroachDB provider
  providers/cockroachdb.js
Labels: Meta: New Pieces

#80 [WIP] Added Lord Of Helps
  commands/General/Chat Bot Info/help.js
Labels: Meta: New Pieces, Type: Enhancement

#83 Add checkChatForImage extendable
  extendables/fetchImage.js
Labels: Meta: New Pieces

#82 General fixes
  commands/Fun/8ball.js
  commands/Fun/choice.js
  commands/Fun/chucknorris.js
  commands/Fun/coinflip.js
  commands/Fun/insult.js
  commands/Fun/yomomma.js
  commands/Misc/echo.js
  commands/Misc/starboard.js
  commands/Moderation/ban.js
  commands/Moderation/check.js
  commands/Moderation/kick.js
  commands/Moderation/mute.js
  commands/Moderation/softban.js
  commands/Moderation/unban.js
  commands/Moderation/unmute.js
  commands/System/prune.js
  commands/Tools/remindme.js
  monitors/everyone.js
  tasks/reminder.js
  tasks/unmute.js
Labels: Meta: Cleanup, Meta: New Pieces, Type: Consistency
