Repository dirigeants/klasa-pieces, pull requests merged in 2018-11, with the labels that each got.

#139 language: klasa#473 Update Klasa for Internal Sharding
  languages/es-ES.js
  languages/fr-FR.js
  languages/ja-JP.js
Labels: Type: Maintenance

#130 Create twitterStream.js
  events/twitterStream.js
Labels: Meta: New Pieces

#131 Add bigint serializer
  serializers/bigint.js
Labels: Meta: New Pieces

#124 Add Spotify commands
  commands/Tools/artist.js
  commands/Tools/song.js
  tasks/getSpotifyToken.js
Labels: Meta: New Pieces

#141 Fixed mongo
  providers/mongodb.js
Labels: Meta: Bug-Fix

#145 Deps: Update `level` provider to use `level`
  providers/level.js
Labels: Meta: Dependencies

#146 Update prefix.js
  commands/Configuration/prefix.js
Labels: Type: Enhancement

#147 Update dog.js
  commands/Misc/dog.js
Labels: Meta: Documentation, Type: Maintenance

#149 Add msg.sendLoading extendable
  extendables/sendLoading.js
Labels: Meta: New Pieces

#148 Add timed reboot command
  commands/System/Admin/reboot.js
Labels: Meta: New Pieces
