Repository dirigeants/klasa-pieces, pull requests merged in 2019-03, with the labels that each got.

#176 modified mongo provider to accept a connection string
  providers/mongodb.js
Labels: Meta: Feature, Type: Enhancement

#179 fixed messageembed fields cannot be empty when role doesn't have explicit permissions
  commands/Tools/role-info.js
Labels: Meta: Bug-Fix

#183 Create waifu.js
  commands/Fun/waifu.js
Labels: Meta: New Pieces

#185 create d20.js
  commands/Fun/d20.js
Labels: Meta: New Pieces

#189 Add a task to backup your json provider's data
  src/tasks/jsonBackup.js
Labels: Meta: New Pieces

#186 Update rethinkdb provider to use rethinkdb-ts module
  providers/rethinkdb.js
Labels: Meta: Dependencies, Meta: Refactor, Type: Maintenance

#191 utilize SnowflakeUtil
  tasks/cleanup.js
Labels: Meta: Refactor

#144 Create reloadOnChanges.js
  tasks/reloadOnChanges.js
Labels: Meta: New Pieces, Status: Changes Requested

#150 Solve rolename.js
  arguments/rolename.js
Labels: Meta: Bug-Fix
