Repository dirigeants/klasa-pieces, pull requests merged in 2019-05, with the labels that each got.

#198 Add ru-RU language
  languages/ru-RU.js
Labels: Meta: New Pieces

#200 Proper way to delete voiceStates.
  tasks/cleanup.js
Labels: Meta: Bug-Fix

#202 add thanosquote command
  commands/Fun/thanosquote.js
Labels: Meta: New Pieces

#201 Add some pieces
  commands/Fun/deobfuscate.js
  commands/Fun/obfuscate.js
  monitors/filter.js
Labels: Meta: New Pieces

#193 Create emoji and emojis route
  routes/emoji.js
  routes/emojis.js
Labels: Meta: New Pieces

#197 Fix typo
  languages/ja-JP.js
Labels: Meta: Bug-Fix, Type: Maintenance

#205 Fixed level.js error.
  providers/level.js
Labels: Meta: Bug-Fix
