Repository dirigeants/klasa-pieces, pull requests merged in 2019-01, with the labels that each got.

#167 Updated the api endpoint for duck command.
  commands/Misc/duck.js
Labels: Type: Maintenance

#168 Adds Traditional Chinese (Taiwan) language piece
  languages/zh-TW.js
Labels: Meta: New Pieces, Type: Enhancement

#165 Add crate command
  commands/Tools/crate.js
Labels: Meta: New Pieces

#157 A personal TODO list
  commands/Tools/todo.js
Labels: Meta: New Pieces
